# Generated by Django 5.2 on 2025-12-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
