# Generated by Django 5.2 on 2025-12-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_url_limit_alter_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url_limit',
        ),
    ]
