# Generated by Django 5.2 on 2025-12-15 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('short_url', models.CharField(unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_alias', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_code/%Y/%m/%d')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expires_time', models.DateTimeField(blank=True, null=True)),
                ('last_clicked', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ShortURL',
                'verbose_name_plural': 'ShortURLs',
            },
        ),
    ]
