# Generated by Django 5.2 on 2025-12-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linko', '0003_alter_shorturl_options_alter_shorturl_short_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_stats', to='Linko.shorturl')),
            ],
            options={
                'verbose_name': 'Click Stat',
                'verbose_name_plural': 'Click Stats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='Linko_click_timesta_b6bc13_idx')],
            },
        ),
    ]
