# Generated by Django 5.2 on 2025-12-19 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('short_code', models.CharField(db_index=True, unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_alias', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_code/%Y/%m/%d')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expires_time', models.DateTimeField(blank=True, null=True)),
                ('last_clicked', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ShortURL',
                'verbose_name_plural': 'ShortURLs',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ClickStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_stats', to='links.shorturl')),
            ],
            options={
                'verbose_name': 'Click Stat',
                'verbose_name_plural': 'Click Stats',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_code'], name='links_short_short_c_35c604_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['created_time'], name='links_short_created_5bba08_idx'),
        ),
        migrations.AddIndex(
            model_name='clickstats',
            index=models.Index(fields=['timestamp'], name='links_click_timesta_f2d2c0_idx'),
        ),
    ]
