# Generated by Django 5.2 on 2025-12-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='short_url',
            new_name='short_code',
        ),
    ]
