# Generated by Django 5.2 on 2025-12-16 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_rename_short_url_shorturl_short_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'ordering': ['-created_time'], 'verbose_name': 'ShortURL', 'verbose_name_plural': 'ShortURLs'},
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_code'], name='Linko_short_short_c_6a3c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['created_time'], name='Linko_short_created_45a986_idx'),
        ),
    ]
